n1 = int(input("กรุณาระบุตัวเลขที่1: "))
n2 = int(input("กรุณาระบุตัวเลขที่2: "))
print(n1,"+",n2,"=",n1+n2 )
print(n1,"-",n2,"=",n1-n2 )
print(n1,"*",n2,"=",n1*n2 )
print(n1,"/",n2,"=",int(n1/n2) )